# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf631953cef2d5e8477387d1e2f6308001a937066b8a105e39f24b96c07856957990e6c526f6c629b50d2d67b713cda9e206e9fe033700e427fc99b9244e3c8

test:
  secret_key_base: 815ca913270c100978111578cc8d5ae37df1df6f8dc6458237fe3bac16b361969b5e54abf9a0b2c3fe25109863cec3e29110526e6ed331111cce9f4037dabf88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
